version: '3.8'

services:
  db:
    image: postgres:14
    container_name: teetime-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teetime
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
    container_name: teetime-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/teetime
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata: